//
//  Created by Vonage on 23/06/2026.
//

import Foundation

/// Data source protocol for retrieving log file URLs.
///
/// Implementations provide access to the log files generated by the
/// SDK logging system. This protocol lives in the Domain layer and is
/// implemented in the Data layer by concrete adapters (e.g. one backed
/// by ``SDKLoggingService``).
///
/// ## Usage
/// ```swift
/// let dataSource: LogFileURLDataSource = ...
/// let urls = dataSource.getLogFileURLs()
/// ```
public protocol LogFileURLDataSource {
    /// Returns the URLs of available log files.
    /// - Returns: An array of file URLs for current SDK log files, or empty if none exist.
    func getLogFileURLs() -> [URL]
}

/// Null-object implementation of ``LogFileURLDataSource`` that always
/// returns an empty array.
///
/// Use as a default when no concrete data source is available (e.g. in
/// previews or when the logging service is not configured).
public struct NullLogFileURLDataSource: LogFileURLDataSource {
    public init() {}

    public func getLogFileURLs() -> [URL] {
        []
    }
}
