//
//  Created by Vonage on 5/2/26.
//

import Foundation

/// Represents a single caption from a speaker in a video call
public struct CaptionItem: Identifiable, Equatable {
    /// Unique identifier for the caption
    public let id: String

    /// Name of the person speaking
    public let speakerName: String

    /// The caption text
    public let text: String

    /// Whether this caption was generated by the local user.
    public let isMe: Bool

    /// When the caption was created
    public let timestamp: Date

    public init(
        id: String = UUID().uuidString,
        speakerName: String,
        text: String,
        isMe: Bool = false,
        timestamp: Date = Date()
    ) {
        self.id = id
        self.speakerName = speakerName
        self.text = text
        self.isMe = isMe
        self.timestamp = timestamp
    }
}
