---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: video-ios-ref-app   # SERVICE NAME field
  title: Video iOS Reference Application   # Title (human-friendly service name) field
  description: An open-source video conferencing reference application for the Vonage Video API using the iOS SDK.
  annotations:
    vonage.com/jira-id: VPF   # video general projects
spec:
  type: service
  owner: group:orgdata/vdk   # helm "owner" orgdata squad id or general orgdata/vid
  domain: video-api   # Product this service belongs to