//
//  Created by Vonage on 23/06/2026.
//

import Foundation

/// Use case protocol for retrieving current SDK log file URLs.
///
/// Implementations provide access to the log files generated by the
/// SDK logging system, typically used for sharing via the Settings UI.
///
/// ## Usage
/// ```swift
/// let getLogFileURLs: GetLogFileURLsUseCase = ...
/// let urls = getLogFileURLs()
/// ```
public protocol GetLogFileURLsUseCase {
    /// Returns the URLs of available log files.
    /// - Returns: An array of file URLs for current SDK log files, or empty if none exist.
    func callAsFunction() -> [URL]
}

/// Default implementation of ``GetLogFileURLsUseCase`` that retrieves
/// log file URLs from a provider closure.
///
/// This bridges the gap between the Settings module and the SDK logging
/// service, which lives in a different module (`VERAVonage`).
public final class DefaultGetLogFileURLsUseCase: GetLogFileURLsUseCase {

    private let provider: () -> [URL]

    /// Creates a new use case with the given URL provider.
    ///
    /// - Parameter provider: A closure that returns the current log file URLs.
    public init(provider: @escaping () -> [URL]) {
        self.provider = provider
    }

    public func callAsFunction() -> [URL] {
        provider()
    }
}
