//
//  Created by Vonage on 23/06/2026.
//

import Foundation

/// Use case protocol for retrieving current SDK log file URLs.
///
/// Implementations provide access to the log files generated by the
/// SDK logging system, typically used for sharing via the Settings UI.
///
/// ## Usage
/// ```swift
/// let getLogFileURLsUseCase: GetLogFileURLsUseCase = ...
/// let urls = getLogFileURLsUseCase()
/// ```
public protocol GetLogFileURLsUseCase {
    /// Returns the URLs of available log files.
    /// - Returns: An array of file URLs for current SDK log files, or empty if none exist.
    func callAsFunction() -> [URL]
}

/// Default implementation of ``GetLogFileURLsUseCase`` that retrieves
/// log file URLs from a ``LogFileURLDataSource``.
///
/// This bridges the gap between the Settings module and the SDK logging
/// service, which lives in a different module (`VERAVonage`).
public final class DefaultGetLogFileURLsUseCase: GetLogFileURLsUseCase {

    private let dataSource: LogFileURLDataSource

    /// Creates a new use case with the given data source.
    ///
    /// - Parameter dataSource: The data source that provides log file URLs.
    public init(dataSource: LogFileURLDataSource) {
        self.dataSource = dataSource
    }

    public func callAsFunction() -> [URL] {
        dataSource.getLogFileURLs()
    }
}
