//
//  Created by Vonage on 19/02/2026.
//

import Foundation
import SwiftUI

/// A display-ready caption item for use in SwiftUI views.
///
/// This is a pure UI model with no domain-layer dependencies.
/// Use ``CaptionItem/toUICaptionItem()`` to convert from the domain model.
public struct UICaptionItem: Identifiable, Equatable {
    /// Unique identifier for the caption.
    public let id: String

    /// Formatted attributed text with a bold speaker name prefix.
    public let text: AttributedString

    /// A VoiceOver-friendly description of the caption.
    public var accessibilityLabel: String

    /// Whether this caption was generated by the local user.
    public let isMe: Bool

    /// When the caption was created.
    public let timestamp: Date

    public init(
        id: String,
        text: AttributedString,
        accessibilityLabel: String,
        isMe: Bool,
        timestamp: Date
    ) {
        self.id = id
        self.text = text
        self.accessibilityLabel = accessibilityLabel
        self.isMe = isMe
        self.timestamp = timestamp
    }
}

// MARK: - Preview Data

#if DEBUG
    extension UICaptionItem {
        static let previewAlice = makePreview(
            speaker: "Alice", text: "Hello everyone, welcome to the meeting!", offset: -6)
        static let previewBob = makePreview(speaker: "Bob", text: "Sure, go ahead!", offset: -5)
        static let previewCharlie = makePreview(speaker: "Charlie", text: "Sounds good to me!", offset: -4)
        static let previewDiana = makePreview(speaker: "Diana", text: "I have a few items to cover.", offset: -3)
        static let previewAlice2 = makePreview(speaker: "Alice", text: "Great, Diana please go first.", offset: -2)
        static let previewDiana2 = makePreview(
            speaker: "Diana", text: "Thanks! The first thing is the new feature release.", offset: -1)
        static let previewLongText = makePreview(
            speaker: "Alice",
            text: "This is a really long caption that should wrap to multiple lines to demonstrate"
                + " how the view handles text that exceeds the available width."
        )

        private static func makePreview(speaker: String, text: String, offset: TimeInterval = 0) -> UICaptionItem {
            var boldPart = AttributedString(speaker + ": ")
            boldPart.font = .system(.footnote, design: .default).bold()
            var regularPart = AttributedString(text)
            regularPart.font = .system(.footnote, design: .default)
            return UICaptionItem(
                id: UUID().uuidString,
                text: boldPart + regularPart,
                accessibilityLabel: "\(speaker) says: \(text)",
                isMe: false,
                timestamp: Date().addingTimeInterval(offset)
            )
        }
    }
#endif
