//
//  Created by Vonage on 10/10/25.
//

import SwiftUI

/// Public versions of the autogenerated colors from the assets file
/// By default are internal to the module
extension SwiftUI.ShapeStyle where Self == SwiftUI.Color {
    public static var accent: Color { .init(.vAccent) }
    public static var label: Color { .init(.uiLabel) }
    public static var secondaryLabel: Color { .init(.uiSecondaryLabel) }
    public static var secondarySystemBackground: Color { .init(.uiSecondarySystemBackground) }
    public static var systemBackground: Color { .init(.uiSystemBackground) }
    public static var gray0: Color { .init(.vGray0) }
    public static var gray1: Color { .init(.vGray1) }
    public static var gray2: Color { .init(.vGray2) }
    public static var gray3: Color { .init(.vGray3) }
    public static var gray4: Color { .init(.vGray4) }
}
