#!/bin/bash

# Generates a Swift file with environment constants and updates entitlements
# Usage: 
#   BASE_API_URL=https://api.example.com/ ./generateEnvironmentConstants.sh
# 
# Exits with error if BASE_API_URL is not set

set -e  # Exit on error

if [ -z "$BASE_API_URL" ]; then
    echo "❌ Error: BASE_API_URL environment variable is not set"
    echo "Usage: BASE_API_URL=https://api.example.com/ ./generateEnvironmentConstants.sh"
    exit 1
fi

# Extract domain from URL (remove protocol and trailing slash)
DOMAIN=$(echo "$BASE_API_URL" | sed -E 's|^https?://||' | sed 's|/$||')

# Output paths
SWIFT_OUTPUT_DIR="VERAApp/VERA/App/Generated"
SWIFT_OUTPUT_FILE="$SWIFT_OUTPUT_DIR/EnvironmentConstants.swift"
ENTITLEMENTS_FILE="VERAApp/VERA/VERA.entitlements"

# Create directory if it doesn't exist
mkdir -p "$SWIFT_OUTPUT_DIR"

# Generate the Swift file
cat > "$SWIFT_OUTPUT_FILE" << EOF
//
// EnvironmentConstants.swift
// VERA
//
// This file is auto-generated by Scripts/generateEnvironmentConstants.sh
// Do not edit manually - your changes will be overwritten
//

import Foundation

enum EnvironmentConstants {
    /// Base API URL for the application
    /// Generated from BASE_API_URL environment variable
    static let baseAPIURL: String = "$BASE_API_URL"
    
    /// Computed URL property for convenience
    static var baseURL: URL {
        guard let url = URL(string: baseAPIURL) else {
            fatalError("Invalid BASE_API_URL: \(baseAPIURL)")
        }
        return url
    }
}
EOF

echo "✅ EnvironmentConstants.swift generated with BASE_API_URL = $BASE_API_URL"
echo "   Output: $SWIFT_OUTPUT_FILE"

# Update entitlements file with associated domain
cat > "$ENTITLEMENTS_FILE" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.developer.associated-domains</key>
    <array>
        <string>applinks:$DOMAIN</string>
    </array>
</dict>
</plist>
EOF

echo "✅ VERA.entitlements updated with applinks:$DOMAIN"
echo "   Output: $ENTITLEMENTS_FILE"