#!/bin/bash

# Generates a Swift file with environment constants and updates entitlements
#
# ⚠️  IMPORTANT: This script must be run BEFORE tuist generate / xcodebuild
#     Do NOT use this as a build phase or scheme pre-action
#     The entitlements file must be stable during the Xcode build process
#
# Usage: 
#   BASE_API_URL=https://api.example.com/ ./generateEnvironmentConstants.sh
# 
# Exits with error if BASE_API_URL is not set

set -e  # Exit on error

# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERA_DIR="$SCRIPT_DIR/.."

# Validate VERA directory exists
if [ ! -d "$VERA_DIR/VERAApp" ]; then
    echo "❌ Error: VERA directory structure not found at $VERA_DIR"
    echo "   Expected to find VERAApp/ folder"
    exit 1
fi

cd "$VERA_DIR"

if [ -z "$BASE_API_URL" ]; then
    echo "❌ Error: BASE_API_URL environment variable is not set"
    echo "Usage: BASE_API_URL=https://api.example.com/ ./generateEnvironmentConstants.sh"
    exit 1
fi

# Extract domain from URL (remove protocol and trailing slash)
DOMAIN=$(echo "$BASE_API_URL" | sed -E 's|^https?://||' | sed 's|/$||')

# Output paths
SWIFT_OUTPUT_DIR="VERAApp/VERA/App/Generated"
SWIFT_OUTPUT_FILE="$SWIFT_OUTPUT_DIR/EnvironmentConstants.swift"
ENTITLEMENTS_FILE="VERAApp/VERA/VERA.entitlements"

# Validate target App directory exists
if [ ! -d "VERAApp/VERA/App" ]; then
    echo "❌ Error: Target directory VERAApp/VERA/App/ not found"
    echo "   Please ensure the project structure is correct"
    exit 1
fi

# Create Generated directory if it doesn't exist
mkdir -p "$SWIFT_OUTPUT_DIR"

write_if_changed() {
    local temp_file="$1"
    local output_file="$2"
    local unchanged_message="$3"
    local updated_message="$4"

    if [ -f "$output_file" ] && cmp -s "$temp_file" "$output_file"; then
        rm "$temp_file"
        echo "$unchanged_message"
    else
        mv "$temp_file" "$output_file"
        echo "$updated_message"
    fi
}

SWIFT_TEMP_FILE="$(mktemp "$SWIFT_OUTPUT_DIR/EnvironmentConstants.swift.XXXXXX")"
ENTITLEMENTS_TEMP_FILE="$(mktemp "VERAApp/VERA/VERA.entitlements.XXXXXX")"
trap 'rm -f "$SWIFT_TEMP_FILE" "$ENTITLEMENTS_TEMP_FILE"' EXIT

# Generate the Swift file
cat > "$SWIFT_TEMP_FILE" << EOF
//
// EnvironmentConstants.swift
// VERA
//
// This file is auto-generated by Scripts/generateEnvironmentConstants.sh
// Do not edit manually - your changes will be overwritten
//

import Foundation

enum EnvironmentConstants {
    /// Base API URL for the application
    /// Generated from BASE_API_URL environment variable
    static let baseAPIURL: String = "$BASE_API_URL"

    static let veraAppGroupIdentifier = "group.com.vonage.VERA"
    
    /// Computed URL property for convenience
    static var baseURL: URL {
        guard let url = URL(string: baseAPIURL) else {
            fatalError("Invalid BASE_API_URL: \(baseAPIURL)")
        }
        return url
    }
}
EOF

write_if_changed \
    "$SWIFT_TEMP_FILE" \
    "$SWIFT_OUTPUT_FILE" \
    "✅ EnvironmentConstants.swift already up to date with BASE_API_URL = $BASE_API_URL" \
    "✅ EnvironmentConstants.swift generated with BASE_API_URL = $BASE_API_URL"
echo "   Output: $SWIFT_OUTPUT_FILE"

# Update entitlements file with associated domain
cat > "$ENTITLEMENTS_TEMP_FILE" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.developer.associated-domains</key>
    <array>
        <string>applinks:$DOMAIN</string>
    </array>
    <key>com.apple.security.application-groups</key>
    <array>
        <string>group.com.vonage.VERA</string>
    </array>
    <key>com.apple.developer.avfoundation.multitasking-camera-access</key>
    <true/>
</dict>
</plist>
EOF

write_if_changed \
    "$ENTITLEMENTS_TEMP_FILE" \
    "$ENTITLEMENTS_FILE" \
    "✅ VERA.entitlements already up to date with applinks:$DOMAIN" \
    "✅ VERA.entitlements updated with applinks:$DOMAIN"
echo "   Output: $ENTITLEMENTS_FILE"
